### ISSUE TITLE
Arial font

### ISSUE THREAD

**Issue by JacquesCarette** [smiths/TCTvMDE#10]
We're faking Arial with Helvetica. Some might notice... we probably should compile the last version on a machine that has Arial on it.  See
https://tex.stackexchange.com/questions/23957/how-to-set-font-to-arial-throughout-the-entire-document
for the details.  That also might make a difference regarding exactly what fits on one page.

**Comment by smiths** [comment]
I guess I should thank you for noticing this @JacquesCarette, but this was a headache I wasn't looking for at the end of the work day!  😄  I'd like to have said nobody will care, but somebody might, so I changed to an Arial font (uarial.sty) in commit 96a152c.  I included comments on how to install uarial.sty on a Mac, since it isn't installed by default.  (I get the impression that it is easier on Windows.)

I also took this opportunity to add a "Preamble" to each document for the common parts of the tex files.  This came up in a previous discussion with @JacquesCarette.

The Arial font did require some wording modifications, so that all of the documents would fit on one page each.
